name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nox-session: ["tests", "compiled", "build", "lint"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Dependencies
        run: python -m pip install -U nox
      - name: Git config
        run: |
          git config --global user.email "gh-actions"
          git config --global user.name "gh-actions"
          git config --global init.defaultBranch main
      - name: Tests
        run: python -m nox -s ${{ matrix.nox-session }}
