name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nox-session: ["tests", "compiled", "generated", "build", "lint"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "gh-actions"
          git config --global user.name "gh-actions"
          git config --global init.defaultBranch main
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install nox
        run: python -m pip install -U nox
      - name: Run tests
        run: python -m nox --non-interactive -s ${{ matrix.nox-session }}
