name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nox-session:
          - tests
          - compiled
          - generated
          - build
          - lint
        old: [false]
        include:
          - nox-session: tests
            old: true
          - nox-session: compiled
            old: true
          - nox-session: build
            old: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "gh-actions"
          git config --global user.name "gh-actions"
          git config --global init.defaultBranch main
      - name: Configure Python 3.7
        if: ${{ matrix.old }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Configure Python 3.10
        if: ${{ !matrix.old }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.nox-session }}-${{ matrix.old }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/noxfile.py') }}
          restore-keys: |
            pip-${{ matrix.nox-session }}-${{ matrix.old }}
      - name: Cache nox session files
        uses: actions/cache@v3
        with:
          path: .nox
          key: nox-${{ matrix.nox-session }}-${{ matrix.old }}-${{ hashFiles('noxfile.py') }}
          restore-keys: |
            nox-${{ matrix.nox-session }}-${{ matrix.old }}-
      - name: Cache pre-commit environments
        if: ${{ matrix.nox-session == 'lint' || matrix.nox-session == 'generated' }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ matrix.nox-session }}-${{ matrix.old }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ matrix.nox-session }}-${{ matrix.old }}-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U nox plumbum
      - name: Optionally install old version of setuptools and pip
        if: ${{ matrix.old }}
        run: python -m pip install pip==21.1.3 setuptools==57.4.0
      - name: Run tests
        run: python -m nox --non-interactive -s ${{ matrix.nox-session }}
        env:
          SYSTEM_SITE_PACKAGES: ${{ matrix.old }}

  update-projects:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U copier PyGithub pre-commit
      - name: Update projects
        run: python scripts/update-projects.py
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
